name: flat build kernel by proton clang
on:
  watch:
    types: [ started ]

  workflow_dispatch:

jobs:
  build:
    name: Build Kernel by ${{ github.actor }}
    runs-on: ubuntu-16.04
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_HARDLINK: "true"
    steps:
      - uses: actions/checkout@v4
      - name: Prepare Configuration
        run: |
          bash utils/travis-build.sh

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with: # Artifact name
          # A file, directory or wildcard pattern that describes what to upload
          path: ./*.img
